//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState ReportSummaryFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["ReportSummaryFormState"]));
            }
            set {
                this["ReportSummaryFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ReportSummaryFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ReportSummaryFormLocation"]));
            }
            set {
                this["ReportSummaryFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ReportSummaryFormSize {
            get {
                return ((global::System.Drawing.Size)(this["ReportSummaryFormSize"]));
            }
            set {
                this["ReportSummaryFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MonthlyBulletinFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MonthlyBulletinFormState"]));
            }
            set {
                this["MonthlyBulletinFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MonthlyBulletinFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MonthlyBulletinFormLocation"]));
            }
            set {
                this["MonthlyBulletinFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MonthlyBulletinFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MonthlyBulletinFormSize"]));
            }
            set {
                this["MonthlyBulletinFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState VesselSummarySettingsFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["VesselSummarySettingsFormState"]));
            }
            set {
                this["VesselSummarySettingsFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point VesselSummarySettingsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["VesselSummarySettingsFormLocation"]));
            }
            set {
                this["VesselSummarySettingsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size VesselSummarySettingsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["VesselSummarySettingsFormSize"]));
            }
            set {
                this["VesselSummarySettingsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState VesselsFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["VesselsFormState"]));
            }
            set {
                this["VesselsFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point VesselsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["VesselsFormLocation"]));
            }
            set {
                this["VesselsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size VesselsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["VesselsFormSize"]));
            }
            set {
                this["VesselsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FrmImportPersonsState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FrmImportPersonsState"]));
            }
            set {
                this["FrmImportPersonsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrmImportPersonsLocation {
            get {
                return ((global::System.Drawing.Point)(this["FrmImportPersonsLocation"]));
            }
            set {
                this["FrmImportPersonsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FrmImportPersonsSize {
            get {
                return ((global::System.Drawing.Size)(this["FrmImportPersonsSize"]));
            }
            set {
                this["FrmImportPersonsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmImportPersonsSplitterPosition {
            get {
                return ((int)(this["FrmImportPersonsSplitterPosition"]));
            }
            set {
                this["FrmImportPersonsSplitterPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormObsViewLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormObsViewLocation"]));
            }
            set {
                this["FormObsViewLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FormObsViewSize {
            get {
                return ((global::System.Drawing.Size)(this["FormObsViewSize"]));
            }
            set {
                this["FormObsViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormObsViewState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormObsViewState"]));
            }
            set {
                this["FormObsViewState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormObsViewSplitterDistance {
            get {
                return ((int)(this["FormObsViewSplitterDistance"]));
            }
            set {
                this["FormObsViewSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point InspectorsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["InspectorsFormLocation"]));
            }
            set {
                this["InspectorsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size InspectorsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["InspectorsFormSize"]));
            }
            set {
                this["InspectorsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState InspectorsFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["InspectorsFormState"]));
            }
            set {
                this["InspectorsFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrmMailLocation {
            get {
                return ((global::System.Drawing.Point)(this["FrmMailLocation"]));
            }
            set {
                this["FrmMailLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FrmMailSize {
            get {
                return ((global::System.Drawing.Size)(this["FrmMailSize"]));
            }
            set {
                this["FrmMailSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FrmMailState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FrmMailState"]));
            }
            set {
                this["FrmMailState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FrmCrewOnBoardSize {
            get {
                return ((global::System.Drawing.Size)(this["FrmCrewOnBoardSize"]));
            }
            set {
                this["FrmCrewOnBoardSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FrmCrewOnBoardState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FrmCrewOnBoardState"]));
            }
            set {
                this["FrmCrewOnBoardState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrmCrewOnBoardLocation {
            get {
                return ((global::System.Drawing.Point)(this["FrmCrewOnBoardLocation"]));
            }
            set {
                this["FrmCrewOnBoardLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FormReportSummarySize {
            get {
                return ((global::System.Drawing.Size)(this["FormReportSummarySize"]));
            }
            set {
                this["FormReportSummarySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormReportSummaryState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormReportSummaryState"]));
            }
            set {
                this["FormReportSummaryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormReportSummaryLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormReportSummaryLocation"]));
            }
            set {
                this["FormReportSummaryLocation"] = value;
            }
        }
    }
}
